### ISSUE TITLE
A means of tilting the VR game space to play laying back.

### ISSUE THREAD

**Issue by Zod1234** [praydog/UEVR#138]
I realize this would be really low priority but I thought I'd request it anyway.

I also realize uevr probably isn't the best place to put this functionally, as it would be ideal at the os level, but sadly oculus, and other software like VD seemingly have no interest in adding this.  ALVR has this, but other issues make it not the preferred platform for me.  Pico has this as a built in option, but afaik no one else.

as topic title, a means of tilting the world playing at a user defined angle for ex. in a lazy boy.

this would be beneficial not only for people wanting to relax, but also for people with various accessobility issues, potential back issues etc.

again, ideally this would be at the os/vr compositor level but I'm all out of breath to hold.

**Comment by whovian64** [comment]
This would be really good.

**Comment by july19jake** [comment]
+1 
I'd really love this feature.

I just had a play session in my reclining chair. I was using the "2D screen" option.  It would be really nice to be able to tilt the screen to a more comfortable viewing angle.

**Comment by july19jake** [comment]
@praydog Hi, I'm a software developer with some C++ experience. Since I'd love this feature, I'm thinking it might be fun to try to tackle this issue myself and help the project.

Would you please be able to answer the following questions?

1) Do you like this feature? Would you plan on merging it in, if I'm able to solve this?

2) I saw your comment about another feature where you stated that such feature can't be supported by the OpenVR/OpenXR drivers. 

The question is: Do you think this feature of tilting the 2D screen is currently doable?

3) I was looking through your code, trying to find the file where the placement of the 2D screen inside the VR space is handled. However, I couldn't find it. Could you please direct me to the right file?

Thank you. And thank you for starting this project. This is amazing! 🙏

**Comment by praydog** [comment]
Added in be2dff432001a24c045fadea6699def157c05a17 as "Recenter Horizon" button.

Nightly/in-development builds can be downloaded from here https://github.com/praydog/UEVR-nightly/releases/latest

**Comment by Zod1234** [comment]
this doesn't work with headaiming.  any plans to make it work with headaiming?  i was hoping this would work with any game regardless of aiming method.
