### ISSUE TITLE
Windows deletes UEVRBackend.dll

### ISSUE THREAD

**Issue by Rumpel384577** [praydog/UEVR#181]
I have tried it very often. No success. 
![Praydog](https://github.com/praydog/UEVR/assets/158622367/ce73b1e5-b21d-4327-8425-666bc37ece7d)

**Comment by Rumpel384577** [comment]
![praydog2](https://github.com/praydog/UEVR/assets/158622367/ef7dd6d0-02d3-440e-b0a5-7e991c160f5f)

**Comment by Curdie** [comment]
Same. I had to disable real-time protection to get it to work.

**Comment by Rumpel384577** [comment]
Now it works. Thanks

**Comment by harbdog** [comment]
Windows Defender is bouncing it:
![image](https://github.com/praydog/UEVR/assets/1300522/fd2096e4-5f66-4d91-ad5f-0959b18f487a)

**Comment by JMVRy** [comment]
Usually, if a tool gets a score of 3/61 on VirusTotal, I'm fine with it, because it's probably safe and it's probably a false positive. [A score of 31/61 on the other hand... I'm not so sure.](https://www.virustotal.com/gui/file/527e9f92474e4915bfdd0b0b7bbbd45a075941c682e734ceb920d0d329942b1e)

![image](https://github.com/praydog/UEVR/assets/77213524/fce7dbaa-38a2-429e-9b5d-fddbb0ed9995)

**Comment by praydog** [comment]
Duplicate issue #79

If you understood what this tool is doing internally, it is no surprise that these vendors are seeing it as suspicious. The project can be compiled and the source code audited. At this time, the [nightly builds](https://github.com/praydog/UEVR-nightly) are not flagged as suspicious, and we are working on getting the executable in there as well.
