### ISSUE TITLE
Wrapper for tricking UEVR into believing an UE game was played

### ISSUE THREAD

**Issue by Bardo-Konrad** [praydog/UEVR#213]
**Is your feature request related to a problem? Please describe.**
Even though many games are created using UE, many creators have their own engines that cannot be used with UEVR.

**Describe the solution you'd like**
Back in the day, when you used helixmod, it modded games based on directx to be playable in 3D. And for OpenGL there was a Wrapper for DirectX, so you could play OpenGL games in 3D.

What the Wrapper for OpenGL is what I am looking for for UEVR for every engine but Unreal. So UEVR could be tricked into thinking it dealt with a UE game.

**Comment by praydog** [comment]
This is an absolutely ridiculous and frankly impossible task. An engine is not a graphics API that can be translated to another in such a manner, in a generic way.

**Comment by praydog** [comment]
There is an example of something like this working with DXU24 (Unreal Engine 1 -> UE5 translator) but this requires a ton of work on an individual engine to translate such work. This cannot be done generically.

**Comment by Bardo-Konrad** [comment]
> This is an absolutely ridiculous task

You need to work on your social skills, that was uncalled for.

**Comment by praydog** [comment]
Just saying it how it is from my perspective of someone who is familiar with the technical complexity of such a task. Did not mean to cause any issue. 

When this issue popped up into my head, going through the issue makes me think of how long I'd be banging my head against a brick wall at the impossibility of doing this according to UEVR's design principles which is why I worded it that way.
