### ISSUE TITLE
First test Ace Combat 7

### ISSUE THREAD

**Issue by kane1371** [praydog/UEVR#25]
I am probably not the only person that has launched AC7 or was waiting specifically for AC7

There are some issues that might actually be fixable in the current settings but I couldn't figure it out.

I launched the game, and pressed inject with OpenXR.
The injection did happen but, some menus are far too wide and I couldn't read what was written as the menu texts sat at the very edge.
In game huds for lock target were shown, but no other hud was shown like the weapon counter, tracker, etc.
Might they be sitting far off?
Also could not change the view to cockpit view no matter what.
Any ideas?

**Comment by praydog** [comment]
These are game specific issues because this game actually has leftover PSVR code, breaking random things and having some UI that changes when you switch to VR. This is out of UEVR's scope and an independent modder will have to come in and look at these issues.

UEVR itself is not going to fix game specific issues like these, and is not planned to.
