### ISSUE TITLE
Unreal Engine v1 Support? (Goat Simulator)

### ISSUE THREAD

**Issue by Peekofwar** [praydog/UEVR#256]
Loaded up Goat Simulator to see if I could play that game in UEVR considering it runs on Unreal Engine, however the only processes that show up in the program is Discord and Rei Pal. Nowhere (even with administrative privileges) is the game to be seen in the selection. I have used UEVR on Palworld, so I know UEVR works on my machine.

What I assume is happening, is that the game engine is so old, that whatever UEVR is using is not present. Goat Simulator runs on UE v1.0.10897 according to Rei Pal.

Would it be possible to support UE 1 at some point in the future, or is this not possible for some technical reason?

**Comment by praydog** [comment]
It doesn't run on UE1. Studios sometimes apply their own versioning to the file which completely deviate from official UE versioning schemes.

It doesn't show up because your game is a 32-bit game which I'm not planning to support at the moment. Plus, it's UE3. UE3 is more of a long term feature request which will end up coming with 32-bit support because they're all mostly 32-bit. There's no promises of support for UE3.

**Comment by Peekofwar** [comment]
Okay.
