### ISSUE TITLE
Robocop can't move gun with quest controller

### ISSUE THREAD

**Issue by Entretoize** [praydog/UEVR#73]
I watched a video of someone playing Robocop and aiming with his controller. But for me only the joystick can move the gun and it's horrible. Does someone have a profile to share or can explain me the problem ?

**Comment by Pande4360** [comment]
This isnt a community page, Join the discord for solutions

**Comment by Warmotor** [comment]
Entretoize - I noticed this, too. So excited to play this, then my gun just kinda pivoted on a central point instead of true 6DOF with the official profile. The arms look awkward at best. Beardo Benjo did a great tutorial on how to get rid of your hands (non-vr game hands are still and weird) and tie the gun to your controller so you can move it freely. Finding the UObjectHook for the weapon mesh took me FOREVER because it's not accessible from the top of the tree and you have to drill down into unrelated menus to find it. So I've got that working, but the gun is currently pointed 90 degrees to the right and the adjustment tool causes UEVR to just close the interface when I select it. I'm going to submit a bug report, when I get it working I'll post a link to a profile that actually works. You are not alone, my friend.

Yo Pande, I respect your call to order - but R:RC is the most popular UE game, the Quest is the most popular HMD at the moment and the official profile is garbage. From a PR point of view, I think addressing this without making the masses go install and learn another platform is a good idea. I'm just a rando tho...

> I watched a video of someone playing Robocop and aiming with his controller. But for me only the joystick can move the gun and it's horrible. Does someone have a profile to share or can explain me the problem ?

**Comment by Entretoize** [comment]
Thank you Warmotor, the only object I found for the hook moved the mesh of the gun but not where it shoots. The UI show everything and could be really cleaner because it show many thing that are unrelated, maybe they should just create a new menu with a tree of all physical objects and (if needed) in each of them all the "components" that are attached...

**Comment by Warmotor** [comment]
> Thank you Warmotor, the only object I found for the hook moved the mesh of the gun but not where it shoots. The UI show everything and could be really cleaner because it show many thing that are unrelated, maybe they should just create a new menu with a tree of all physical objects and (if needed) in each of them all the "components" that are attached...

I'm sure the UI will improve, these are the earliest days of this mod :) Just to clarify, you attached the gun mesh to your right hand, then changed your aiming method in the basic settings from "game" to "right"? If you've got your gun moving freely with your touch controller and pointed in the correct direction you're at least as close as I am. I am currently shooting where the reticle is, the reticle tracks my right hand, the damn gun model is still pointed off to the right. Did you find a rotation setting for it, or has yours always pointed downrange?

**Comment by Entretoize** [comment]
I don't know what you mean by "basic settings from "game" to "right"" I didn't find that...
Also I don't find the right UObjectHook no more there are too badly organized

**Comment by Warmotor** [comment]
> I don't know what you mean by "basic settings from "game" to "right"" I didn't find that... Also I don't find the right UObjectHook no more there are too badly organized

You are correct, the weapon mesh is buried way deep in the menu tree. On the very first page of the UEVR settings, without going into the Uobjecthook menu, there is an aiming option - it's set to 'Game' by default. If you set it to 'Right Hand' it should switch your bullet path from your eyes to your right motion controller, and if the weapon mesh is attached to your right hand the bullets should appear to come from there. I really wish someone would either make a profile that actually works, or fix the weapon adjust function so I can point my gun downrange. I've never spent this long trying to get a mod to work...

**Comment by Entretoize** [comment]
![Screenshot (1)](https://github.com/praydog/UEVR/assets/405838/5bb22794-30cd-4a83-ab2a-b6a477fa6b86)

This setting ?

**Comment by Entretoize** [comment]
[RoboCop-Win64-Shipping.zip](https://github.com/praydog/UEVR/files/13901148/RoboCop-Win64-Shipping.zip)

This profile works !

**Comment by Entretoize** [comment]
Also this video is good for other games : https://www.youtube.com/watch?v=kH6z6XGusCo

**Comment by praydog** [comment]
Closing this because this is not UEVR's responsibility to make bespoke modifications or have ready made configurations for individual games. UEVR is a generic tool, giving power to the users to make these configurations or plugins.

You should head to the Flat2VR Discord for user made configurations or plugins.

**Comment by Entretoize** [comment]
But it should be good to have a tab with shared configurations between users and that's a programming thing. 
The config already existed and it should have taken 1 minutes to find it but it tooks a week. You tool is really cool, but it can be better.

**Comment by Warmotor** [comment]
> [RoboCop-Win64-Shipping.zip](https://github.com/praydog/UEVR/files/13901148/RoboCop-Win64-Shipping.zip)
> 
> This profile works !

Sorry dude, but it absolutely does not work for me. The gun doesn't move with my hand, it kind of just floats in a static place and rotates on a central axis to point at the crosshair. I've gotten it detached and it tracks my hand, the hook is buried way in the branches of the tree, but doing that broke it so it only points 90deg to the right. The adjust function doesn't bring up the blue box and I can't find rotation params for it. I've been yelling into the void asking for a solution, you'd think if the team wanted to gain attention for the project they'd make it work for the most popular UE5 title - as far as I can tell no one with the technical know how is willing to dig into the objeck hooks and no one who wants to play the game has figured it out.
